### ISSUE TITLE
Minimizing to tray on startup doesn't work with autolaunch

### ISSUE THREAD

**Issue by Enrico204** [Enrico204/Whatsapp-Desktop#8]
Minimizing to tray on startup doesn't work with autolaunch on Gnome DE (on ArchLinux)

(issue reported by @ceyhunnabiyev )

**Comment by Enrico204** [comment]
To @ceyhunnabiyev
I installed a VM with ArchLinux and GNOME 3, and if I copy `whatsapp-desktop.desktop` into `~/.config/autostart/` (for autostart on boot) everything is working (eg. if I checked "minimize on startup", the app is start minimized on login). Please check if you have a duplicate `.desktop` file into that folder.

**Comment by ceyhunnabiyev** [comment]
@Enrico204 ,
After enabling  Minimizing to tray on startup and clicking save button, I tested following events separately:
**1. Quit the application, then restart the computer, then Minimizing to tray on startup works.
2. restart the application, then on tray mode restart the computer, then system freezes.
3. restart the application, click on tray icon for showing application, then  restart the computer,  then Minimizing to tray on startup doesn't work and doesn't save    Minimizing to tray on startup option in setting.**

**Comment by Enrico204** [comment]
Which version of Whatsapp-Desktop are you using?

**Comment by ceyhunnabiyev** [comment]
0.3.9

**Comment by Enrico204** [comment]
I've just released v0.3.10, can you please check with that?
Latest version has "auto-launch" option, so you can remove any manual setting and use the checkbox into settings to configure auto launch at login.
I did some tests with 0.3.10 and auto launch, and I can't reproduce those issues (with a clean ArchLinux and Gnome3 installation), so I hope that latest version resolve these problems ;-)

**Comment by ceyhunnabiyev** [comment]
Thanks a lot, @Enrico204. It's been fixed. I tested all ways that I' ve written the above, no any problem occurred.. Fantastic work!!

**Comment by ceyhunnabiyev** [comment]
Oops, the problem still occurred on me after shutdown.
@Enrico204 , Where do you save the options? I think  something like some whatsapp-desktop file is damaged or corrupted after reboot or shutdown?

**Comment by Enrico204** [comment]
Uhm, this is really strange. Preferences are saved into `~/.config/whatsapp-desktop/settings.json` but only when you hit "Save" on settings view.
`whatsapp-desktop.desktop` should be created in `~/.config/autostart/` only when you enable "Autostart on boot" option.
Usually I don't use Gnome, so maybe there is some strange behavior like "session saving" that interfere with some settings. I'll try again :-)

**Comment by ceyhunnabiyev** [comment]
Strange is that this happens sometimes. After logout or restart or shutdown  my ~/.config/whatsapp-desktop/settings.json becomes empty.

**Comment by ceyhunnabiyev** [comment]
@Enrico204 , please make logging system for your app. Maybe during shutdown or restart or logout, the app crash occurs, then dbus-daemon damages session configurations.

**Comment by Enrico204** [comment]
I've checked again the source code, and I spotted a "close" even hander that saves current configuration (it's used to reopen window at last position). Maybe the configuration variable is empty at that point (for no good reason). That will explain the empty config. Or, maybe the app gets killed before the end of write() call.

Is the `settings.json` an empty file (eg. no content)? Or an empty JSON array/object (eg. `[]` or `{}`, or `null`)? The former may be caused by "killed-before-write", the latter may be caused by empty JSON variable. Even if it contains 1 char, it might be important, let me know :-)

Yes a logging system would be nice. I've opened an issue for that (#10) to track that.

**Comment by ceyhunnabiyev** [comment]
> Is the settings.json an empty file (eg. no content)? Or an empty JSON array/object (eg. [] or {}, or null)?

Empty. There is nothing in here (something like you create an Empty Document)

**Comment by ceyhunnabiyev** [comment]
Does writeFileSync automatically do flushing and close events  for files immediately?

**Comment by Enrico204** [comment]
In theory, yes. In practice, that function may be not "atomic".

Ok, two (mutual) scenarios are in my mind:
 - `config.currentSettings` is `undefined` -> `JSON.stringify` returns `undefined` -> `writeFileSync` translate `undefined` to empty when writing (I need to prove it)
 - `writeFileSync` is interrupted in the middle of execution (eg. in underlying syscalls: after `open(filename, O_WRONLY | O_CREAT | O_TRUNC)` and before `write()`)

The former is unlikely our issue I think, but it's easy to fix. I think that we may test it first, just in case.

**Comment by ceyhunnabiyev** [comment]
However  I always  notice that selected options is  saved  in settings.json .. Something is happened during killing the app.  After shutdown(logout, restart) I immediately looks at settings.json  before the app is started the file is empty.

**Comment by Enrico204** [comment]
can you please download the latest master and check if this problem still exists?
(I solved the first hypotesis)

**Comment by ceyhunnabiyev** [comment]
I  download latest whatsapp-linux64.zip or git clone for rebuilding manually?

**Comment by Enrico204** [comment]
git clone and build manually. If you have issue with that I can build a version for you :-)

**Comment by ceyhunnabiyev** [comment]
@Enrico204 , I have tested  so many ways. Nothing happened. It works. Perhaps suddenly it will occur, I don't know.

**Comment by Enrico204** [comment]
So weird behavior. Maybe we should keep this issue opened for few days. If the problem recurs please reply here. If not, I'll close the issue.
In the meantime I'll work on #10 (logging system). Maybe we'll understand this behavior by looking at the logs.

**Comment by ceyhunnabiyev** [comment]
Yes, if the problem occurs again, I will return back.

Regards...

**Comment by Enrico204** [comment]
Thanks @ceyhunnabiyev for the patience and for the help you provided me :-)

**Comment by ceyhunnabiyev** [comment]
The problem occurred again after yesterday shutdown.  Just ignore this please, I can use the app, it is not a  serious problem. After you implement the logging system, we will return back to this problem, I will give you  detailed info  with logs.

**Comment by Enrico204** [comment]
Hi @ceyhunnabiyev , version 0.3.11 has logging capabilities. Can you please update and try again? Also, there is a command-line option to raise logging to debug level.

**Comment by ceyhunnabiyev** [comment]
Hi @Enrico204 , I have problem with internet provider. On Saturday, I will return back..

**Comment by Enrico204** [comment]
No problem :-)

**Comment by ceyhunnabiyev** [comment]
Hi @Enrico204 , I don't have the problem yet like  not to  save Minimizing to tray on startup option in setting, but I see one error in log.log file after logout:

`[2017-08-06 15:04:38:0679] [warn] Error clearing cache: Error: ENOENT: no such file or directory, unlink '/home/ceyhun/.config/whatsapp-desktop/Application Cache/Index'
`

**Comment by ceyhunnabiyev** [comment]
Hi @Enrico204 , issue occurred on me today:
[log.zip](https://github.com/Enrico204/Whatsapp-Desktop/files/1219534/log.zip)

**Comment by Enrico204** [comment]
Uhm, I'll try to reproduce this issue again and compare log files. Thanks :-)

**Comment by ceyhunnabiyev** [comment]
@Enrico204 , But I can't see any severe error inside log.

**Comment by Enrico204** [comment]
You're right. In fact, that's the reason why I need to go deep and understand how that is possible. In the meantime, can you please modify your shortcuts (eg. `.desktop` file) to execute WhatsApp with command line parameter `--debug-log`?
(this switch should increase log verbosity)

**Comment by ceyhunnabiyev** [comment]
I modified:
```
[Desktop Entry]
Type=Application
Name=WhatsApp Desktop
Icon=whatsapp-desktop
Exec=Whatsapp --debug-log
Comment=WhatsApp for Desktop
Categories=Network;Chat;
Terminal=false
StartupNotify=true
```

**Comment by Enrico204** [comment]
thanks :-)

**Comment by ceyhunnabiyev** [comment]
Hi @Enrico204 ,  issue occurred again:
[log.zip](https://github.com/Enrico204/Whatsapp-Desktop/files/1230182/log.zip)

**Comment by ceyhunnabiyev** [comment]
Hi @Enrico204 , the problem occurred again:
[log.zip](https://github.com/Enrico204/Whatsapp-Desktop/files/1236855/log.zip)

**Comment by Enrico204** [comment]
There is nothing wrong according to these logs. So, I need to improve logging and I need to do some heavy testing on ArchLinux. I'll install Arch on my laptop as soon as I have some spare time. Just one question: do you leave WhatsApp running on logout?
(in other words, do you close WhatsApp manually before logout or not?)

**Comment by ceyhunnabiyev** [comment]
No,  I Don't close before logout

**Comment by ceyhunnabiyev** [comment]
@Enrico204  , Maybe any confuse between facebook messenger and whatsapp? 
Both of them use electron:

![screenshot-20170821235501-676x453](https://user-images.githubusercontent.com/5506156/29535861-97c48406-86cc-11e7-93ad-cc3b0274fe73.png)
![screenshot-20170821235547-680x401](https://user-images.githubusercontent.com/5506156/29535869-9f92f816-86cc-11e7-8254-d6bfbd350570.png)

**Comment by ceyhunnabiyev** [comment]
Sadly both of them eat my RAM.

**Comment by ceyhunnabiyev** [comment]
Hi @Enrico204 , Maybe this gonna help you, You know that I have no problem with facebook messenger. That's why I note here 4 commands with options of both applications (Four commands were showed on the pictures that I gave screenshots above)  

**Messenger Commands:**

> /usr/lib/electron/electron --type=renderer --no-sandbox --primordial-pipe-token=_something_ --lang=en-US --node-integration=false --preload=/usr/lib/messengerfordesktop/scripts/renderer/preload/index.js --guest-instance-id=1 --enable-blink-features --disable-blink-features --hidden-page --enable-pinch --num-raster-threads=4 --content-image-texture-target=_something_ --video-image-texture-target=_something_ --disable-accelerated-video-decode --disable-webrtc-hw-encoding --disable-gpu-compositing --mojo-channel-token=_something_ --mojo-application-channel-token=_something_ --channel=_something_ --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd

> /usr/lib/electron/electron --type=renderer --no-sandbox --primordial-pipe-token=_something_ --lang=en-US --node-integration=true --background-color=#ffffff --hidden-page --enable-pinch --num-raster-threads=4 --content-image-texture-target=_something_ --video-image-texture-target=_something_ --disable-accelerated-video-decode --disable-webrtc-hw-encoding --disable-gpu-compositing --mojo-channel-token=_something_ --mojo-application-channel-token=_something_ --channel=_something_ --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd

> /usr/lib/electron/electron --type=zygote --no-sandbox

> /usr/lib/electron/electron --os-startup /usr/bin/messengerfordesktop


**Whatsapp Commands**

> /opt/Whatsapp/Whatsapp --type=renderer --no-sandbox --primordial-pipe-token=_something_ --lang=en-US --node-integration=false --preload=/opt/Whatsapp/resources/app/js/injected.js  --hidden-page --enable-pinch --num-raster-threads=4 --content-image-texture-target=_something_ --video-image-texture-target=_something_ --disable-accelerated-video-decode --mojo-channel-token=_something_ --mojo-application-channel-token=_something_ --channel=_something_ --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd


> /opt/Whatsapp/Whatsapp --type=gpu-process --channel=_something_ --mojo-application-channel-token=_something_  --no-sandbox --window-depth=24 --x11-visual-id=_something_ --supports-dual-gpus=false --gpu-driver-bug-workarounds=_something_ --gpu-vendor-id=_something_ --gpu-device-id=_something_ --gpu-driver-vendor --gpu-driver-version --gpu-driver-date --gpu-secondary-vendor-ids=_something_ --gpu-secondary-device-ids=_something_ --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd


> /opt/Whatsapp/Whatsapp  --type=zygote --no-sandbox


> /opt/Whatsapp/Whatsapp

**Comment by Enrico204** [comment]
I think that the issue is on "save-on-exit" feature that is supposed to save some window preferences. Maybe we can try disabling that. I'll commit the code ASAP.

**Comment by Enrico204** [comment]
Hi @ceyhunnabiyev , can you try with the latest revision of `master` branch? Thanks :-)

**Comment by ceyhunnabiyev** [comment]
I have done, just waiting :-)

**Comment by ceyhunnabiyev** [comment]
Hi @Enrico204 , still no problem.

**Comment by Enrico204** [comment]
I removed the save-on-exit feature, I'm releasing the v0.3.13 with that fix :-)
Please reopen this issue if this problem occurs again :-)

**Comment by ceyhunnabiyev** [comment]
Hi @Enrico204 , For 10 days, I've not had this issue. Thanks for fix.
